### ISSUE TITLE
Logo For Moshey

### ISSUE THREAD

**Issue by zularizal** [Davidodari/Moshey#1]
Hi @Davidodari , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by Davidodari** [comment]
Yeah Sure, it's welcome. It's all open source. @zularizal

**Comment by zularizal** [comment]
Hi @Davidodari , this is the design logo for your project. This logo is inspired by a pin map and train icon.

The color that I choose is matched with the appearance of your app.
And also I have made an icon, which one do you like? 1 or 2?

If there is anything you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/55680183-70fe3e00-5940-11e9-9238-36ab69e891ca.png)

**Comment by Davidodari** [comment]
Those are pretty sleek designs,i love the first one it shos both primary and accent

> Hi @Davidodari , this is the design logo for your project. This logo is inspired by a pin map and train icon.
> 
> The color that I choose is matched with the appearance of your app.
> And also I have made an icon, which one do you like? 1 or 2?
> 
> If there is anything you want to change, let me know.
> 
> ![bitmap](https://user-images.githubusercontent.com/38547278/55680183-70fe3e00-5940-11e9-9238-36ab69e891ca.png)

Those are pretty sleek designs,i love the first one it shos both primary and accent

**Comment by zularizal** [comment]
Hi @Davidodari , I have sent a pull request. #6 

And also I have uploaded the logo to the drive. Check this link.
https://drive.google.com/open?id=1Ht8XH_1sBM_a-NG5qc3G6zOHIm_XepXY

**Comment by Davidodari** [comment]
Ive merged the PR ,the design work on the readme is awesome too
